"""Content generators — llms.txt and fix pack ZIP."""

import io
import json
import zipfile
from datetime import date

import httpx
from bs4 import BeautifulSoup
from fastapi import APIRouter
from fastapi.responses import PlainTextResponse, StreamingResponse
from pydantic import BaseModel
from typing import List
from urllib.parse import urlparse, urljoin

router = APIRouter(tags=["generate"])

HEADERS = {
    "User-Agent": "AISEOSetup/1.0 (+https://aiseo.setup; llms-txt-generator)",
    "Accept": "text/html,application/xhtml+xml,*/*;q=0.8",
}
TIMEOUT = httpx.Timeout(12.0, connect=5.0)


class GenerateRequest(BaseModel):
    url: str


def _base(url: str) -> str:
    p = urlparse(url)
    return f"{p.scheme}://{p.netloc}"


def _clean(text: str) -> str:
    return " ".join(text.split()) if text else ""


async def _fetch(client: httpx.AsyncClient, url: str) -> str | None:
    try:
        r = await client.get(url, headers=HEADERS, timeout=TIMEOUT, follow_redirects=True)
        if r.status_code == 200 and "text" in r.headers.get("content-type", ""):
            return r.text
    except Exception:
        pass
    return None


def _extract_nav_links(soup: BeautifulSoup, base: str) -> list[tuple[str, str]]:
    """Extract navigation links as (title, url) pairs."""
    links = []
    seen = set()
    # Try nav elements first, then header links
    for container in soup.select("nav, header"):
        for a in container.find_all("a", href=True):
            href = a["href"].strip()
            text = _clean(a.get_text())
            if not text or len(text) > 60:
                continue
            full = urljoin(base, href)
            if full.startswith(base) and full not in seen:
                seen.add(full)
                links.append((text, full))
    return links[:20]


def _extract_sections(soup: BeautifulSoup) -> list[str]:
    """Extract main section headings."""
    sections = []
    for tag in soup.find_all(["h2", "h3"]):
        text = _clean(tag.get_text())
        if text and 3 < len(text) < 120:
            sections.append(text)
    return sections[:15]


def _parse_sitemap(xml: str, base: str) -> list[str]:
    """Extract URLs from sitemap XML."""
    soup = BeautifulSoup(xml, "html.parser")
    urls = []
    for loc in soup.find_all("loc"):
        url = loc.get_text().strip()
        if url.startswith(base):
            urls.append(url)
    return urls[:50]


def _build_llms_txt(url: str, title: str, description: str,
                    nav: list[tuple[str, str]], sections: list[str],
                    sitemap_urls: list[str]) -> str:
    lines = []
    domain = urlparse(url).netloc

    lines.append(f"# {title or domain}")
    lines.append("")
    if description:
        lines.append(f"> {description}")
        lines.append("")

    lines.append(f"Source: {url}")
    lines.append("")

    if nav:
        lines.append("## Navigation")
        lines.append("")
        for name, href in nav:
            lines.append(f"- [{name}]({href})")
        lines.append("")

    if sections:
        lines.append("## Page Sections")
        lines.append("")
        for s in sections:
            lines.append(f"- {s}")
        lines.append("")

    if sitemap_urls:
        lines.append("## Site Pages")
        lines.append("")
        for u in sitemap_urls[:30]:
            lines.append(f"- {u}")
        lines.append("")

    lines.append("---")
    lines.append("Generated by [Agentable](https://seo4agent.com) — Agent Readiness Auditor")

    return "\n".join(lines)


@router.post("/generate/llms-txt")
async def generate_llms_txt(req: GenerateRequest):
    url = req.url.strip().rstrip("/")
    if not url.startswith("http"):
        url = "https://" + url
    base = _base(url)

    async with httpx.AsyncClient(follow_redirects=True) as client:
        html = await _fetch(client, url)
        sitemap_xml = await _fetch(client, f"{base}/sitemap.xml")

    title = ""
    description = ""
    nav: list[tuple[str, str]] = []
    sections: list[str] = []

    if html:
        soup = BeautifulSoup(html, "html.parser")
        title_tag = soup.find("title")
        title = _clean(title_tag.get_text()) if title_tag else ""
        og_title = soup.find("meta", property="og:title")
        if og_title and og_title.get("content"):
            title = _clean(og_title["content"])

        meta_desc = soup.find("meta", attrs={"name": "description"})
        if meta_desc and meta_desc.get("content"):
            description = _clean(meta_desc["content"])
        og_desc = soup.find("meta", property="og:description")
        if og_desc and og_desc.get("content"):
            description = _clean(og_desc["content"])

        nav = _extract_nav_links(soup, base)
        sections = _extract_sections(soup)

    sitemap_urls: list[str] = []
    if sitemap_xml:
        sitemap_urls = _parse_sitemap(sitemap_xml, base)

    content = _build_llms_txt(url, title, description, nav, sections, sitemap_urls)
    filename = f"llms-{urlparse(url).netloc}.txt"
    return PlainTextResponse(
        content=content,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ── Fix Pack ZIP generator ────────────────────────────────────────────────────

class FixPackRequest(BaseModel):
    url: str
    failed_checks: List[str]  # list of check_ids that failed


def _make_robots_patch(domain: str) -> str:
    return f"""# Add these rules to your existing robots.txt
# Generated by Agentable — https://seo4agent.com
# Deploy at: https://{domain}/robots.txt

User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: Amazonbot
Allow: /
"""


def _make_security_txt(domain: str) -> str:
    return f"""Contact: mailto:security@{domain}
Expires: {date.today().replace(year=date.today().year + 1).isoformat()}T23:59:59.000Z
Preferred-Languages: en
Policy: https://{domain}/security-policy
Canonical: https://{domain}/.well-known/security.txt
# Generated by Agentable — https://seo4agent.com
# Deploy at: https://{domain}/.well-known/security.txt
"""


def _make_mcp_json(domain: str) -> str:
    return json.dumps({
        "mcpServers": [
            {
                "name": f"{domain}-api",
                "description": f"MCP server for {domain}",
                "url": f"https://{domain}/mcp",
                "transport": "http",
                "version": "1.0.0",
                "tools": []
            }
        ]
    }, indent=2) + f"\n# Deploy at: https://{domain}/.well-known/mcp.json\n"


def _make_schema_jsonld(domain: str, title: str, description: str) -> str:
    schema = {
        "@context": "https://schema.org",
        "@type": "WebApplication",
        "name": title or domain,
        "url": f"https://{domain}",
        "description": description or f"Visit {domain}",
        "applicationCategory": "WebApplication",
        "operatingSystem": "Any",
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"}
    }
    snippet = f'<script type="application/ld+json">\n{json.dumps(schema, indent=2)}\n</script>'
    return f"""<!-- Schema.org JSON-LD — add inside <head> of your HTML -->
<!-- Generated by Agentable — https://seo4agent.com -->
{snippet}
"""


def _make_og_tags(domain: str, title: str, description: str) -> str:
    return f"""<!-- Open Graph meta tags — add inside <head> of your HTML -->
<!-- Generated by Agentable — https://seo4agent.com -->
<meta property="og:type" content="website" />
<meta property="og:url" content="https://{domain}/" />
<meta property="og:title" content="{title or domain}" />
<meta property="og:description" content="{description or ''}" />
<meta property="og:image" content="https://{domain}/og-image.png" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{title or domain}" />
<meta name="twitter:description" content="{description or ''}" />
"""


CHECK_ADVICE: dict[str, str] = {
    "l1_semantic": "Add semantic HTML5 elements: <header>, <nav>, <main>, <article>, <section>, <footer>",
    "l1_ssr": "Enable Server-Side Rendering (SSR) or Static Site Generation (SSG) — Next.js, Nuxt, Astro, etc.",
    "l1_title": "Add a descriptive <title> tag to your HTML",
    "l1_metadesc": "Add <meta name='description' content='...'> to your HTML head",
    "l1_og": "Add Open Graph meta tags — see og-tags.html in this pack",
    "l1_schema": "Add Schema.org JSON-LD markup — see schema-jsonld.html in this pack",
    "l2_robots": "Create or update /robots.txt to allow AI crawlers — see robots-patch.txt",
    "l2_sitemap": "Create /sitemap.xml listing all your main pages",
    "l2_llmstxt": "Publish /llms.txt describing your product for AI agents — see llms.txt in this pack",
    "l2_openapi": "Publish an OpenAPI spec at /openapi.json for machine-readable API docs",
    "l2_securitytxt": "Publish /.well-known/security.txt — see security.txt in this pack",
    "l3_agentcard": "Publish /.well-known/ai-plugin.json or an agent card describing your capabilities",
    "l3_jsonapi": "Expose a REST or GraphQL API returning JSON responses",
    "l3_ratelimit": "Add rate limit headers (X-RateLimit-Limit, X-RateLimit-Remaining) to API responses",
    "l3_cors": "Enable CORS headers (Access-Control-Allow-Origin) on your API endpoints",
    "l4_mcp": "Implement an MCP (Model Context Protocol) server at /mcp",
    "l4_webmcp": "Publish /.well-known/mcp.json for WebMCP discovery — see mcp.json in this pack",
    "l4_webhooks": "Add webhook endpoints (/webhooks) for async agent notifications",
    "l4_auth": "Support API key or OAuth 2.0 client credentials for agent authentication",
    "l4_x402": "Implement x402 payment protocol (HTTP 402 + x-payment headers) for agent-native payments",
    "l5_streaming": "Add SSE or WebSocket endpoints for real-time event streaming",
    "l5_subscriptions": "Build a subscription API (/subscriptions) for agents to manage data feeds",
    "l5_manifest": "Publish /.well-known/ai-plugin.json agent manifest for cross-service discovery",
}


def _make_readme(domain: str, files: list[str], failed_checks: list[str]) -> str:
    lines = [
        f"# Fix Pack for {domain}",
        f"Generated by Agentable (https://seo4agent.com) on {date.today().isoformat()}",
        "",
    ]
    if files:
        deploy_map = {
            "robots-patch.txt": f"Merge into https://{domain}/robots.txt",
            ".well-known/security.txt": f"Deploy at https://{domain}/.well-known/security.txt",
            ".well-known/mcp.json": f"Deploy at https://{domain}/.well-known/mcp.json",
            "schema-jsonld.html": "Add the <script> tag inside <head> of your HTML",
            "og-tags.html": "Add the <meta> tags inside <head> of your HTML",
            "llms.txt": f"Deploy at https://{domain}/llms.txt",
        }
        lines += ["## Files included", ""]
        for f in files:
            lines.append(f"- **{f}** — {deploy_map.get(f, 'See file for instructions')}")
        lines.append("")

    lines += ["## Full fix checklist", ""]
    for cid in failed_checks:
        advice = CHECK_ADVICE.get(cid, f"Fix check: {cid}")
        lines.append(f"- [ ] **{cid}**: {advice}")

    lines += ["", "## Re-audit after deploying", f"https://seo4agent.com"]
    return "\n".join(lines)


@router.post("/generate/fix-pack")
async def generate_fix_pack(req: FixPackRequest):
    url = req.url.strip().rstrip("/")
    if not url.startswith("http"):
        url = "https://" + url
    base = _base(url)
    domain = urlparse(url).netloc

    # Fetch site for title/description (needed for OG/schema)
    title, description = "", ""
    async with httpx.AsyncClient(follow_redirects=True) as client:
        html = await _fetch(client, url)
        sitemap_xml = await _fetch(client, f"{base}/sitemap.xml")
        nav: list[tuple[str, str]] = []
        sections: list[str] = []
        if html:
            soup = BeautifulSoup(html, "html.parser")
            og_title = soup.find("meta", property="og:title")
            title_tag = soup.find("title")
            title = _clean(og_title["content"]) if og_title and og_title.get("content") else (
                _clean(title_tag.get_text()) if title_tag else domain)
            og_desc = soup.find("meta", property="og:description")
            meta_desc = soup.find("meta", attrs={"name": "description"})
            description = _clean(og_desc["content"]) if og_desc and og_desc.get("content") else (
                _clean(meta_desc["content"]) if meta_desc and meta_desc.get("content") else "")
            nav = _extract_nav_links(soup, base)
            sections = _extract_sections(soup)
        sitemap_urls = _parse_sitemap(sitemap_xml, base) if sitemap_xml else []

    checks = set(req.failed_checks)
    files: dict[str, str] = {}

    if "l2_robots" in checks or "l0_block" in checks:
        files["robots-patch.txt"] = _make_robots_patch(domain)

    if "l2_securitytxt" in checks:
        files[".well-known/security.txt"] = _make_security_txt(domain)

    if "l4_webmcp" in checks or "l4_mcp" in checks:
        files[".well-known/mcp.json"] = _make_mcp_json(domain)

    if "l1_schema" in checks:
        files["schema-jsonld.html"] = _make_schema_jsonld(domain, title, description)

    if "l1_og" in checks:
        files["og-tags.html"] = _make_og_tags(domain, title, description)

    if "l2_llmstxt" in checks:
        llms_content = _build_llms_txt(url, title, description, nav, sections, sitemap_urls)
        files["llms.txt"] = llms_content

    files["README.md"] = _make_readme(domain, list(files.keys()), req.failed_checks)

    # Build ZIP in memory
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, content in files.items():
            zf.writestr(name, content)
    buf.seek(0)

    filename = f"agentable-fixes-{domain}.zip"
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
